# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
context:
  version: "2025_08_07"

package:
  name: acpica-tools
  version: ${{ version | replace('_', '') }}

source:
  url: https://github.com/acpica/acpica/archive/refs/tags/${{ version | replace('_', '') }}.tar.gz
  sha256: 971df1f78944e5f3bb314209acbf8a127c0db34b4a3c26e011b4076eba1c2bbc

build:
  number: 0
  script: |
    make PREFIX=$PREFIX OPT_CFLAGS="-DACPI_PACKED_POINTERS_NOT_SUPPORTED"
    make install PREFIX=$PREFIX
  skip: not unix

requirements:
  build:
    - make
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - bison
    - flex
    - m4

tests:
  - script: acpihelp -u

about:
  license: Intel-ACPI OR GPL-2.0-only
  license_file: LICENSE
  summary: OS-independent implementation of the ACPI specification
  description: |
    ACPICA (ACPI Component Architecture) project provides an OS-independent
    reference implementation of the Advanced Configuration and Power Interface
    Specification (ACPI).
  homepage: https://www.acpica.org/
  repository: https://github.com/acpica/acpica
  documentation: https://www.acpica.org/

extra:
  recipe-maintainers:
    - hameerabbasi
